{"id":"36238520206","type":"IssueCommentEvent","actor":{"id":44127594,"login":"Ahajha","display_login":"Ahajha","gravatar_id":"","url":"https://api.github.com/users/Ahajha","avatar_url":"https://avatars.githubusercontent.com/u/44127594?"},"repo":{"id":204671232,"name":"conan-io/conan-center-index","url":"https://api.github.com/repos/conan-io/conan-center-index"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863","repository_url":"https://api.github.com/repos/conan-io/conan-center-index","labels_url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863/labels{/name}","comments_url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863/comments","events_url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863/events","html_url":"https://github.com/conan-io/conan-center-index/issues/22863","id":2149900268,"node_id":"I_kwDODDMJAM6AJN_s","number":22863,"title":"[package] xz_utils/5.4.5 Package sources/tar not found at URL","user":{"login":"Lnk2past","id":6456398,"node_id":"MDQ6VXNlcjY0NTYzOTg=","avatar_url":"https://avatars.githubusercontent.com/u/6456398?v=4","gravatar_id":"","url":"https://api.github.com/users/Lnk2past","html_url":"https://github.com/Lnk2past","followers_url":"https://api.github.com/users/Lnk2past/followers","following_url":"https://api.github.com/users/Lnk2past/following{/other_user}","gists_url":"https://api.github.com/users/Lnk2past/gists{/gist_id}","starred_url":"https://api.github.com/users/Lnk2past/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Lnk2past/subscriptions","organizations_url":"https://api.github.com/users/Lnk2past/orgs","repos_url":"https://api.github.com/users/Lnk2past/repos","events_url":"https://api.github.com/users/Lnk2past/events{/privacy}","received_events_url":"https://api.github.com/users/Lnk2past/received_events","type":"User","site_admin":false},"labels":[{"id":1521573798,"node_id":"MDU6TGFiZWwxNTIxNTczNzk4","url":"https://api.github.com/repos/conan-io/conan-center-index/labels/bug","name":"bug","color":"d73a4a","default":true,"description":"Something isn't working"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2024-02-22T20:40:59Z","updated_at":"2024-03-04T21:42:41Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Description\n\nI tried installing `xz_utils/5.4.5` and Conan times out because the URL in the package is not correct.\r\n\r\n```text\r\nxz_utils/5.4.5: WARN: network: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'\r\n```\r\n\r\nI think the problem is that the website https://tukaani.org is no longer valid, and should be https://xz.tukaani.org/. The links to the actual tars look different now too; so I think all of the URLs in conandata.yml are incorrect.\n\n### Package and Environment Details\n\n* Package Name/Version: **xz_utils/5.4.5**\r\n* Operating System+version: **Linux Ubuntu 20.04**\r\n* Compiler+version: **GCC 10.2**\r\n* Docker image: N/A\r\n* Conan version: **conan 2.0.17**\r\n* Python version: **Python 3.9.2**\r\n\n\n### Conan profile\n\n[settings]\r\narch=x86_64\r\nbuild_type=Debug\r\ncompiler=gcc\r\ncompiler.cppstd=20\r\ncompiler.libcxx=libstdc++11\r\ncompiler.version=12\r\nos=Linux\n\n### Steps to reproduce\n\nconan install --requires=xz_utils/5.4.5 -r conancenter --build=missing\n\n### Logs\n\n<details><summary>Click to expand log</summary>\r\n\r\n```\r\n======== Input profiles ========\r\nProfile host:\r\n[settings]\r\narch=x86_64\r\nbuild_type=Debug\r\ncompiler=gcc\r\ncompiler.cppstd=20\r\ncompiler.libcxx=libstdc++11\r\ncompiler.version=12\r\nos=Linux\r\n\r\nProfile build:\r\n[settings]\r\narch=x86_64\r\nbuild_type=Debug\r\ncompiler=gcc\r\ncompiler.cppstd=20\r\ncompiler.libcxx=libstdc++11\r\ncompiler.version=12\r\nos=Linux\r\n\r\n\r\n======== Computing dependency graph ========\r\nGraph root\r\n    cli\r\nRequirements\r\n    xz_utils/5.4.5#a26a2d42ab9c3dabc151bbe1bf898e53 - Cache\r\n\r\n======== Computing necessary packages ========\r\nRequirements\r\n    xz_utils/5.4.5#a26a2d42ab9c3dabc151bbe1bf898e53:1a9fda660de0c747d126d629ab86cd194228796f - Build\r\n\r\n======== Installing packages ========\r\nxz_utils/5.4.5: WARN: Trying to remove corrupted source folder\r\nxz_utils/5.4.5: WARN: This can take a while for big packages\r\nxz_utils/5.4.5: Calling source() in /root/.conan2/p/xz_ute033bfcacc0c2/s/src\r\nxz_utils/5.4.5: WARN: network: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'\r\nxz_utils/5.4.5: Waiting 5 seconds to retry...\r\nxz_utils/5.4.5: WARN: network: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'\r\nxz_utils/5.4.5: Waiting 5 seconds to retry...\r\nERROR: xz_utils/5.4.5: Error in source() method, line 77\r\n        get(self, **self.conan_data[\"sources\"][self.version], strip_root=True)\r\n        ConanException: Error downloading file https://tukaani.org/xz/xz-5.4.5.tar.xz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.4.5.tar.xz (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))'\r\n```\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863/timeline","performed_via_github_app":null,"state_reason":null},"comment":{"url":"https://api.github.com/repos/conan-io/conan-center-index/issues/comments/1977511404","html_url":"https://github.com/conan-io/conan-center-index/issues/22863#issuecomment-1977511404","issue_url":"https://api.github.com/repos/conan-io/conan-center-index/issues/22863","id":1977511404,"node_id":"IC_kwDODDMJAM513m3s","user":{"login":"Ahajha","id":44127594,"node_id":"MDQ6VXNlcjQ0MTI3NTk0","avatar_url":"https://avatars.githubusercontent.com/u/44127594?v=4","gravatar_id":"","url":"https://api.github.com/users/Ahajha","html_url":"https://github.com/Ahajha","followers_url":"https://api.github.com/users/Ahajha/followers","following_url":"https://api.github.com/users/Ahajha/following{/other_user}","gists_url":"https://api.github.com/users/Ahajha/gists{/gist_id}","starred_url":"https://api.github.com/users/Ahajha/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Ahajha/subscriptions","organizations_url":"https://api.github.com/users/Ahajha/orgs","repos_url":"https://api.github.com/users/Ahajha/repos","events_url":"https://api.github.com/users/Ahajha/events{/privacy}","received_events_url":"https://api.github.com/users/Ahajha/received_events","type":"User","site_admin":false},"created_at":"2024-03-04T21:42:39Z","updated_at":"2024-03-04T21:42:39Z","author_association":"CONTRIBUTOR","body":"Seems related to [this](https://github.com/tukaani-project/xz/issues/78), which seems to also support that it was a temporary outage.","reactions":{"url":"https://api.github.com/repos/conan-io/conan-center-index/issues/comments/1977511404/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2024-03-04T21:42:41Z","org":{"id":15212165,"login":"conan-io","gravatar_id":"","url":"https://api.github.com/orgs/conan-io","avatar_url":"https://avatars.githubusercontent.com/u/15212165?"}}
